<a href="https://colab.research.google.com/github/Battula-Shilpa/-Python/blob/main/6_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- linear algebra library in python
- Used for performing mathematical and logical operations
- provides features for operations on multi-dimensional and matrices in python

# **Basics**

In [ ]:
import numpy as np

In [ ]:
# 1D array
a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [ ]:
a[0]

1

In [ ]:
a[1:4]

array([2, 3, 4])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,0])
print(a)
print(b)

[1 2 3 4 5]
[6 7 8 9 0]


In [ ]:
# 2D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
arr.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
arr[0]

array([1, 2, 3])

In [ ]:
arr[1]

array([4, 5, 6])

In [ ]:
arr[:0]

array([], shape=(0, 3), dtype=int64)

In [ ]:
arr[0:]

array([[1, 2, 3],
       [4, 5, 6]])

- **Numpy array initialization**

In [ ]:
#Zero array
a = np.zeros([3,4])
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
a = np.array([10,25,5])
print(a)

[10 25  5]


In [ ]:
# np.arange(start,end,step)
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [ ]:
arr = np.arange(10)
print(arr)
arr.shape

[0 1 2 3 4 5 6 7 8 9]


(10,)

In [ ]:
arr = np.arange(6)
a = arr.reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [ ]:
arr.size

6

In [ ]:
#np.linspace(start,end,number of points)
arr = np.linspace(1,10, 4)
print(arr)

[ 1.  4.  7. 10.]


In [ ]:
arr = np.linspace(0,1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


- **Fill SAME number in a array of dimension x X y**

In [ ]:
import numpy as np
#np.full((row,column),numbertofill
arr = np.full((3,4),5)
print(arr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
np.full((2,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

 - **filling RANDOM numbers in array of dimension x X y**

In [ ]:
import numpy as np
arr = np.random.random((2,3)) # tuple
print(arr)

[[0.65155281 0.20382033 0.67749148]
 [0.01446544 0.04573357 0.20274254]]


In [ ]:
arr = np.random.rand(2, 1, 5)
print(arr)

[[[0.07345219 0.83196922 0.89247254 0.94295852 0.87037264]]

 [[0.4488247  0.11605765 0.50304926 0.8069565  0.60605975]]]


In [ ]:
arr = np.random.rand(2,3)
print(arr)

[[0.30053628 0.15879851 0.44164734]
 [0.87200133 0.76446693 0.53623482]]


In [ ]:
arr = np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


- **ndim array**

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)

2


In [ ]:
a.shape = (3,2)
print(a.shape[0])
print(a.shape[1])
print(a.ndim) # returns the number of dimensions of the array
print(a)

3
2
2
[[1 2]
 [3 4]
 [5 6]]


- **dtype**
  - Returns datatype of an array

In [ ]:
import numpy as np
a = np.arange(24,dtype = float)
print(a.size)
print(a.dtype)
b = a.reshape(3,4,2)
print(b)

24
float64
[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]
  [ 6.  7.]]

 [[ 8.  9.]
  [10. 11.]
  [12. 13.]
  [14. 15.]]

 [[16. 17.]
  [18. 19.]
  [20. 21.]
  [22. 23.]]]


In [ ]:
b = np.linspace(5,3,2)
print(b.dtype)

float64


- **Mathematical calculations**

In [ ]:
# Addition
import numpy as np
np.sum([10,20])

30

In [ ]:
a,b = 10,20
np.sum([a,b])

30

In [ ]:
np.sum([[2,1],[6,4]],axis = 0)

array([8, 5])

In [ ]:
np.sum([[1,3],[4,6]],axis = 1)

array([ 4, 10])

In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(np.add(arr1,arr2)) # a+b
print(np.subtract(arr1,arr2)) # a-b
print(np.multiply(arr1,arr2)) # a*b
print(np.divide(arr1,arr2))   #a/b
print(np.exp(a)) #e^a
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.log(a))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
22026.465794806718
3.1622776601683795
-0.5440211108893698
-0.8390715290764524
2.302585092994046


In [ ]:
a = ([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.corrcoef(a))

21
1
6
3.5
3.5
1.707825127659933
2.9166666666666665
[[1. 1.]
 [1. 1.]]


- **Boradcasting**

In [ ]:
import numpy as np
a = np.array([[9,0,0],[2,3,5],[4,6,8]])
b = np.array([1,2,3])
print(a+b)

[[10  2  3]
 [ 3  5  8]
 [ 5  8 11]]


In [ ]:
print(a)

[[9 0 0]
 [1 2 3]
 [2 3 5]]


In [ ]:
print(b)

[4 6 8]


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
sum_along_columns = np.sum(arr,axis=0)
print("Sum along columns (axis =0):",sum_along_columns)

sum_along_rows = np.sum(arr,axis=1)
print("Sum along rows (axis =1):",sum_along_rows)

Sum along columns (axis =0): [5 7 9]
Sum along rows (axis =1): [ 6 15]


- **Indexing and Slicing**
   - Indexing : Refer the position
   - slicing : extract the element

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0])
print(a[:1])
print(a[:0])
print(a[1:2])
print(a[0:1])
print(a[:,1:]) #slicing

[[1 2 3]
 [4 5 6]]
[1 2 3]
[[1 2 3]]
[]
[[4 5 6]]
[[1 2 3]]
[[2 3]
 [5 6]]


In [ ]:
arr_2d =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

#slicing
print(arr_2d[1, :])
print(arr_2d[:, 1])
print(arr_2d[:,-1])
print(arr_2d[::-1])
print(arr_2d[0:2,0:2])
print(arr_2d[::2,::2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[2 5 8]
[3 6 9]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[1 2]
 [4 5]]
[[1 3]
 [7 9]]


In [ ]:
print(arr_2d[:2,2:])

[[3]
 [6]]


In [ ]:
#concatenate
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(a)
print(b)
np.concatenate((a,b),axis=0)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[1,2,3],[4,5,6]])
np.concatenate((a,b),axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- **Array Manipulation**

In [ ]:
# Array Manipulation
# stacking doesnot work in 2D array
print(np.stack((a,b),axis=0))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#hstack
print(np.hstack((c,d)))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [ ]:
#vstack
print(np.vstack((c,d)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print("A matrix")
print(a)
print("B matrix")
print(b)
print("---Horizontal stack---")
print(np.hstack((a,b)))
print("---Horizontal Concatenate---")
print(np.concatenate((a,b),axis=0))
print("---Vertical stack---")
print(np.vstack((a,b)))
print("---Vetical Concatenate---")
print(np.concatenate((a,b),axis=1))

A matrix
[[1 2 3]
 [4 5 6]]
B matrix
[[ 7  8  9]
 [10 11 12]]
---Horizontal stack---
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
---Horizontal Concatenate---
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
---Vertical stack---
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
---Vetical Concatenate---
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


- **Spliting Array**

In [ ]:
X = np.arange(16.0).reshape(4,4)
print(X,"\n\n")
print(np.hsplit(X,2),"\n\n")
print(np.vsplit(X,2),"\n\n")

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]] 


[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])] 


[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])] 




In [ ]:
print(X)
print(np.split(X,2,axis=0))
print(np.split(X,2,axis=1))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


In [ ]:
print(np.split(X,4,axis=1))

[array([[ 0.],
       [ 4.],
       [ 8.],
       [12.]]), array([[ 1.],
       [ 5.],
       [ 9.],
       [13.]]), array([[ 2.],
       [ 6.],
       [10.],
       [14.]]), array([[ 3.],
       [ 7.],
       [11.],
       [15.]])]


In [ ]:
X[:,:1]

array([[ 0.],
       [ 4.],
       [ 8.],
       [12.]])

In [ ]:
X[:1,:2]

array([[0., 1.]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(arr1, arr2)

print(dot_product)

[[19 22]
 [43 50]]


In [ ]:
arr = np.array([1,2,3,4,5])
filtered = arr[arr>3]
print(filtered)

[4 5]


In [ ]:
import numpy as np
arr = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
new_arr = np.append(arr,new_row,axis=0)
print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
arr = np.array([[1,2],[3,4]])
new_column = np.array([[5],[6]])
new_arr = np.append(arr, new_column, axis=1)
print(new_arr)

[[1 2 5]
 [3 4 6]]


In [ ]:
import numpy as np
arr = np.array([[1,2],[3,4]])
new_arr = np.delete(arr,1,axis=0)
print(new_arr)

[[1 2]]


In [ ]:
import numpy as np
arr = np.array([[1,2],[3,4]])
new_row = np.array([99, 100])
new_arr = np.insert(arr,1,new_row,axis=1)
print(new_arr)

# **Example**

In [ ]:
#Numpy vs List : Memory size
import numpy as np
import sys

#define a list
l = range(1000)
print(l)
print("Size of a list:",sys.getsizeof(5)*len(l))

#define a numpy array
a = np.arange(1000)
print("Size of an array:",a.size*a.itemsize)

range(0, 1000)
Size of a list: 28000
Size of an array: 8000
range(0, 1000)
